# Generated by Django 4.2.5 on 2023-09-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="created_by",),
    ]
